### ISSUE TITLE
Concurrency VS Parallelism

### ISSUE THREAD

**Issue by sonrose** [selab-hs/selab-month-study-1#1]
동시성과 병렬성 알아보다 궁금한 게 생겨 질문합니다~!
멀티태스킹이 동시성을 만족하는 건 알겠는데, 병렬성도 만족하나요?
멀티태스킹은 프로세스가 짧은 시간 동안 번갈아가면서 일을 처리하기 때문에 **여러 프로그램이 동시에 처리되는 것처럼 보이는 거**라고 알고 있는데, 병렬성은 실제로 한 번에, 동시에 여러 일을 처리하는 거잖아요?
그래서 병렬성은 만족하지 않는다고 이해했습니다.
그런데 검색해 보니 멀티태스킹이 병렬성도 만족한다는 글을 봐서 헷갈려서 질문 드려요~!
제가 이해한 게 맞을까요?

@DongGeon0908

**Comment by DongGeon0908** [comment]
@sonrose 
참고하신 자료를 확인할 수 있을까요???
해당 문제는 특정 상황에 따라 달라질 수 있다고 생각되네요!!

해당 블로그에 그림을 잘 설명되어 있네요!!

https://deveun.tistory.com/entry/OS-%EB%A9%80%ED%8B%B0%ED%83%9C%EC%8A%A4%ED%82%B9-%EB%A9%80%ED%8B%B0%ED%94%84%EB%A1%9C%EC%84%B8%EC%8B%B1-%EB%A9%80%ED%8B%B0%EC%8A%A4%EB%A0%88%EB%93%9C

**Comment by sonrose** [comment]
@DongGeon0908 

https://codedragon.tistory.com/5468
요거 보고 헷갈렸습니다 ^^;;

그런데 파이프라인 기법을 보고 나니 병렬성(병렬 처리)도 만족할 수 있는 것 같네요
아직 각 개념들이 완전히 정리되지 않아서 헷갈리긴 하지만 조금 더 공부하면 알 수 있을 것 같습니다!!!!!!!!!!

**Comment by DongGeon0908** [comment]
concurrency한게 무엇인지, 그리고 parallelism이 무엇인지만 안다면 된 것 같아요~~!
그 다음 내용은 로즈님이 더 깊게 공부하시면 좋을 것 같아요!!

공부하시고, 저에게도 공유좀...부탁드릴게요 :)
